_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: 101
    WITH_IBN: True
    PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet101_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 1041

SOLVER:
  MAX_ITER: 42000
  STEPS: [19000, 33000]
  WARMUP_ITERS: 4700
  CHECKPOINT_PERIOD: 5000

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "logs/msmt17/bagtricks_R101-ibn"

